objects/Expense__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <label>Event</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Expense</label>
    <nameField>
        <displayFormat>E-{000}</displayFormat>
        <label>EventID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ExpenseMemberAssociation__c.object
<CustomObject>
    <fields>
        <fullName>ContributionAmount__c</fullName>
        <label>ContributionAmount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>ExpenseID__c</fullName>
        <label>Expense</label>
        <referenceTo>Expense__c</referenceTo>
        <relationshipLabel>Expense</relationshipLabel>
        <relationshipName>ExpenseMemberAssociations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MemberID__c</fullName>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Member</relationshipLabel>
        <relationshipName>ExpenseMemberAssociations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ExpenseMemberAssociation</label>
    <nameField>
        <displayFormat>EM-{000}</displayFormat>
        <label>EventMemberAssociation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ExpenseMemberAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>FirstName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>LastName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>M-{000}</displayFormat>
        <label>MemberID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ExpenseEXT_Test.cls
@isTest
public class ExpenseEXT_Test {
    
    public static testmethod void test1(){
    
    Expense__c expobj = new Expense__c();
    expobj.Amount__c=5000;
    expobj.Description__c='friends shopping';
    expobj.Event__c='shopping';
    insert expobj;
    
    Member__c memobj = new Member__c();
    memobj.Email__c='ipsita@optimizeitsystems.com';
    memobj.FirstName__c='Ipsita';
    memobj.LastName__c='Dutta';
    insert memobj;
    
    
    ExpenseMemberAssociation__c emaobj = new ExpenseMemberAssociation__c();
    emaobj.ExpenseID__c=expobj.id;
    emaobj.MemberID__c=memobj.id;
    emaobj.ContributionAmount__c=1000;
    insert emaobj;
    ExpenseEXT obj = new ExpenseEXT (new ApexPages.StandardController(expobj));
    List<ExpenseMemberAssociation__c> ge = new List<ExpenseMemberAssociation__c>();
    ge = obj.getExpMembers();
        
    }
}