objects/Expense__c.object
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>E-{000}</displayFormat>
        <label>EventID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ExpenseMemberAssociation__c.object
<CustomObject>
    <fields>
        <fullName>ContributionAmount__c</fullName>
        <label>ContributionAmount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ExpenseID__c</fullName>
        <label>Expense</label>
        <referenceTo>Expense__c</referenceTo>
        <relationshipLabel>Expense</relationshipLabel>
        <relationshipName>ExpenseMemberAssociations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MemberID__c</fullName>
        <label>Member</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>Member</relationshipLabel>
        <relationshipName>ExpenseMemberAssociations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ExpenseMemberAssociation</label>
    <nameField>
        <displayFormat>EM-{000}</displayFormat>
        <label>EventMemberAssociation ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ExpenseMemberAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>FirstName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Member</label>
    <nameField>
        <displayFormat>M-{000}</displayFormat>
        <label>MemberID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ExpenseEXT.cls
public with sharing class ExpenseEXT {
    public Expense__c expObj{get;set;}
    public List<ExpenseMemberAssociation__c> memExp{get;set;}

    public ExpenseEXT(ApexPages.StandardController controller) {
        expObj = (Expense__c)controller.getRecord();
        memExp = getExpMembers();
    }
    
    public List<ExpenseMemberAssociation__c> getExpMembers(){
        return [Select ContributionAmount__c, MemberID__r.FirstName__c from ExpenseMemberAssociation__c where ExpenseID__c =: expObj.Id];
    }
}